// Sky Lounge — Menu Data (exact PDF order & prices)

// ══════════════════════════════════════
//  DINING MENU
//  Section order exactly as in PDF pages
// ══════════════════════════════════════
const DINING_MENU = {
  tabs: [
    { id:'all',        label:'All' },
    { id:'soup',       label:'🍲 Soup' },
    { id:'chinese',    label:'🥢 Chinese' },
    { id:'tandoori',   label:'🔥 Tandoori' },
    { id:'exotic',     label:'✨ Exotica' },
    { id:'seafood',    label:'🐟 Sea Food' },
    { id:'sizzler',    label:'🫕 Sizzlers' },
    { id:'egg',        label:'🥚 Egg' },
    { id:'momos',      label:'🥟 Momos' },
    { id:'pasta',      label:'🍝 Pasta' },
    { id:'raita',      label:'🥛 Curd Raita' },
    { id:'papad',      label:'🫓 Papad' },
    { id:'salad',      label:'🥗 Salad' },
    { id:'accomp',     label:'🧂 Accompaniments' },
    { id:'italian',    label:'🍕 Italian & Mexican' },
    { id:'main',       label:'🍛 Main Course' },
    { id:'breads',     label:'🍞 Breads' },
    { id:'dal',        label:'🫕 Dal' },
    { id:'rice',       label:'🍚 Rice & Biryani' },
    { id:'dessert',    label:'🍮 Desserts' },
  ],
  sections: [

    // PAGE 1 — Soup
    { label:"Soup — Veg", emoji:"🌿", tab:"soup", items:[
      {name:"Cream of Tomato Soup",price:195,badge:"veg"},
      {name:"Veg Clear Soup",price:195,badge:"veg"},
      {name:"Veg Manchow Soup",price:195,badge:"veg"},
      {name:"Veg Hot N Sour Soup",price:195,badge:"veg"},
      {name:"Veg Lemon Coriander Soup",price:195,badge:"veg"},
      {name:"Veg Sweet Corn Soup",price:205,badge:"veg"},
      {name:"Veg Dumpling Soup",price:220,badge:"veg"},
      {name:"Veg Garlic Italian Style Soup",price:220,badge:"veg"},
    ]},
    { label:"Soup — Non Veg", emoji:"🍗", tab:"soup", items:[
      {name:"Cream of Chicken Soup",price:260,badge:"non-veg"},
      {name:"Chicken Clear Soup",price:260,badge:"non-veg"},
      {name:"Chicken Lemon Coriander Soup",price:260,badge:"non-veg"},
      {name:"Chicken Hot and Sour Soup",price:260,badge:"non-veg"},
      {name:"Chicken Manchow Soup",price:260,badge:"non-veg"},
      {name:"Chicken Sweet Corn Soup",price:260,badge:"non-veg"},
      {name:"Chicken Dumpling Soup",price:275,badge:"non-veg"},
      {name:"Thai Chicken Noodles Soup",price:275,badge:"non-veg"},
    ]},

    // PAGE 2 — Chinese Starters Veg
    { label:"Chinese Starters — Veg", emoji:"🥢", tab:"chinese", items:[
      {name:"Exotic Vegetable",desc:"Choice of sauce: Hot Garlic, Peri Peri, Barbeque, Peprico",price:395,badge:"veg"},
      {name:"Veg Spring Roll",price:395,badge:"veg"},
      {name:"Veg Manchurian",price:325,badge:"veg"},
      {name:"Veg Crispy",price:325,badge:"veg"},
      {name:"Crispy Chilli Baby Corn",price:395,badge:"veg"},
      {name:"Paneer Spinach Chilli",desc:"Chef's Special",price:395,badge:"veg"},
      {name:"Mushroom Chilli / Paneer Chilli / Chana Chilli",price:395,badge:"veg"},
      {name:"Crispy Honey Chilli Potato",price:395,badge:"veg"},
      {name:"Kung Pao Potatoes",price:395,badge:"veg"},
      {name:"Paneer Bang Bang",price:395,badge:"veg"},
      {name:"Kung Pao Paneer",price:395,badge:"veg"},
      {name:"Burnt Garlic Paneer Chilli",price:425,badge:"veg"},
      {name:"Corn Crispy",price:325,badge:"veg"},
      {name:"Cheese Corn Ball",price:395,badge:"veg"},
      {name:"Paneer Pesto",desc:"Chef's Special",price:425,badge:"veg"},
      {name:"Veg Dragon Roll in Hot Garlic Sauce",price:395,badge:"veg"},
      {name:"American Chopsuey",price:395,badge:"veg"},
      {name:"Dragon Potatoes",desc:"Chef's Special",price:395,badge:"veg"},
      {name:"Vegetable Schezwan Finger",price:395,badge:"veg"},
    ]},

    // PAGE 3 — Rice & Noodles Veg (appears before Chinese Non-Veg in PDF)
    { label:"Rice & Noodles — Veg", emoji:"🍜", tab:"rice", items:[
      {name:"Veg Hakka Noodles",price:335,badge:"veg"},
      {name:"Veg Singapore-Style Noodles",price:345,badge:"veg"},
      {name:"Veg Fried Rice",price:335,badge:"veg"},
      {name:"Veg Schezwan Fried Rice",price:375,badge:"veg"},
      {name:"Veg Burnt Garlic Noodles",price:375,badge:"veg"},
      {name:"Schezwan Hakka Noodles",price:375,badge:"veg"},
      {name:"Veg Triple Schezwan Fried Rice",price:425,badge:"veg"},
      {name:"Veg Cheese Mexican Rice",desc:"Two layered cheese Mexican rice",price:395,badge:"veg"},
    ]},
    { label:"Rice & Noodles — Non Veg", emoji:"🍗", tab:"rice", items:[
      {name:"Chicken Hakka Noodles",price:445,badge:"non-veg"},
      {name:"Chicken Burnt Garlic Noodles",price:475,badge:"non-veg"},
      {name:"Egg Fried Rice",price:385,badge:"non-veg"},
      {name:"Chicken Burnt Garlic Fried Rice",price:455,badge:"non-veg"},
      {name:"Chicken Fried Rice",price:445,badge:"non-veg"},
      {name:"Chicken Schezwan Fried Rice",price:475,badge:"non-veg"},
      {name:"Chicken Triple Schezwan Fried Rice",price:525,badge:"non-veg"},
    ]},

    // PAGE 4 — Chinese Starters Non Veg
    { label:"Chinese Starters — Non Veg", emoji:"🍗", tab:"chinese", items:[
      {name:"Chicken Hot Pan",price:535,badge:"non-veg"},
      {name:"Chicken Bang Bang",price:535,badge:"non-veg"},
      {name:"Chicken Lollipop",price:535,badge:"non-veg"},
      {name:"Chicken Peprico",price:535,badge:"non-veg"},
      {name:"Kung Pao Chicken",desc:"Chef's Special",price:525,badge:"non-veg"},
      {name:"Chicken Crispy",price:515,badge:"non-veg"},
      {name:"Chicken Spring Roll",price:515,badge:"non-veg"},
      {name:"Chicken Spinach Chilli",desc:"Chef's Special",price:535,badge:"non-veg"},
      {name:"Chicken Salt & Pepper",price:515,badge:"non-veg"},
      {name:"Chicken Koliwada",price:515,badge:"non-veg"},
      {name:"Chicken Chopsuey",price:535,badge:"non-veg"},
      {name:"Chicken Chilli (Dry/Gravy)",price:535,badge:"non-veg"},
      {name:"Chicken Wings in Hot Garlic Sauce",price:545,badge:"non-veg"},
      {name:"Drums of Heaven",price:555,badge:"non-veg"},
      {name:"Crispy Chicken Schezwan Finger",desc:"Chef's Special",price:535,badge:"non-veg"},
      {name:"Chicken Barbeque in Hot Pan Sauce",price:565,badge:"non-veg"},
    ]},

    // PAGE 5 — Tandoori Starters Veg
    { label:"Tandoori Starters — Veg", emoji:"🔥", tab:"tandoori", items:[
      {name:"Paneer Peshawari Tikka",price:455,badge:"veg"},
      {name:"Paneer Rozali Tikka",desc:"Chef's Special",price:475,badge:"veg"},
      {name:"Paneer Malai Tikka",price:455,badge:"veg"},
      {name:"Saunfia Paneer Tikka",desc:"Chef's Special",price:455,badge:"veg"},
      {name:"Paneer Angara Tikka",price:455,badge:"veg"},
      {name:"Classic Cheese Paneer Tikka",desc:"Chef's Special",price:475,badge:"veg"},
      {name:"Paneer Cheese Loaded Tikka",desc:"Chef's Special",price:475,badge:"veg"},
      {name:"Paneer Pattaya Tikka",desc:"Chef's Special",price:455,badge:"veg"},
      {name:"Cheese Chilli Corn Seekh Kabab",price:425,badge:"veg"},
      {name:"Paneer Papadi Tikka",price:455,badge:"veg"},
      {name:"Hara Bhara Kabab",price:375,badge:"veg"},
      {name:"Veg Seekh Kabab",price:375,badge:"veg"},
      {name:"Tandoori Atishi Aloo",price:450,badge:"veg"},
      {name:"Palak Corn Cheese Seekh Kabab",desc:"Chef's Special",price:425,badge:"veg"},
      {name:"Tandoori Stuffed Mushroom",desc:"Chef's Special",price:475,badge:"veg"},
      {name:"Beetroot Tikki",desc:"Chef's Special",price:425,badge:"veg"},
      {name:"Tandoori Veg Platter",price:975,badge:"veg"},
    ]},

    // PAGE 6 — Tandoori Starters Non Veg
    { label:"Tandoori Starters — Non Veg", emoji:"🍖", tab:"tandoori", items:[
      {name:"Chicken Hot Pan",price:535,badge:"non-veg"},
      {name:"Chicken Tikka Rice Paper Roll",desc:"Chef's Special",price:565,badge:"non-veg"},
      {name:"Bhatti Ka Murgh Tikka",price:535,badge:"non-veg"},
      {name:"Chicken Rozali Kebab",desc:"Chef's Special",price:550,badge:"non-veg"},
      {name:"Chicken Lababdar Wings (6 pcs)",desc:"Chef's Special",price:550,badge:"non-veg"},
      {name:"Chicken Seekh Laziz",price:535,badge:"non-veg"},
      {name:"Minash Chicken Tikka",desc:"Chef's Special",price:535,badge:"non-veg"},
      {name:"Chicken Tikka",price:535,badge:"non-veg"},
      {name:"Chicken Lasooni Tikka",price:535,badge:"non-veg"},
      {name:"Murgh Kosha",desc:"Chef's Special",price:535,badge:"non-veg"},
      {name:"Mutton Kosha",desc:"Chef's Special",price:645,badge:"non-veg"},
      {name:"Chicken Malai Tikka",price:535,badge:"non-veg"},
      {name:"Mutton Gilafi Seekh Kebab",price:625,badge:"non-veg"},
      {name:"Tandoori Chicken (Half)",price:625,badge:"non-veg"},
      {name:"Tandoori Chicken (Full)",price:895,badge:"non-veg"},
      {name:"Non-Veg Platter",desc:"Chef's Special",price:1450,badge:"non-veg"},
    ]},

    // PAGE 7 — Sky Lounge Exotica
    { label:"Sky Lounge Exotica", emoji:"✨", tab:"exotic", items:[
      {name:"Cheese Peprika Corn Roll",price:435,badge:"veg"},
      {name:"Hara Bhara Loaded Kabab",desc:"Chef's Special",price:425,badge:"veg"},
      {name:"Peri Peri Paneer Popcorn",price:435,badge:"veg"},
      {name:"Potato Croquettes",price:455,badge:"veg"},
      {name:"Dry Yellow Laphing",price:175,badge:"veg"},
      {name:"Paneer Cheese Rice Paper Roll",price:465,badge:"veg"},
      {name:"Paneer Bullet",price:449,badge:"veg"},
      {name:"Cheese Paneer Cigar Roll",price:455,badge:"veg"},
      {name:"Chicken Dynamite",price:565,badge:"non-veg"},
      {name:"Chicken Bullet",price:535,badge:"non-veg"},
      {name:"Chicken Chatkara Tikka",price:625,badge:"non-veg"},
      {name:"Chicken Firdoshi Kebab",price:625,badge:"non-veg"},
      {name:"Chicken Sharabi Tikka",price:675,badge:"non-veg"},
      {name:"Chicken Tangdi Kebab",price:675,badge:"non-veg"},
    ]},

    // PAGE 8 — Sea Food & Sizzlers
    { label:"Sea Food", emoji:"🐟", tab:"seafood", items:[
      {name:"Crispy Fish Fry",price:795,badge:"non-veg"},
      {name:"Fish Koliwada",price:775,badge:"non-veg"},
      {name:"Fish Chilli",price:775,badge:"non-veg"},
      {name:"Fish Schezwan Tikka",price:775,badge:"non-veg"},
      {name:"Fish Lemon Tikka",price:775,badge:"non-veg"},
      {name:"Fish Lasooni Tikka",price:795,badge:"non-veg"},
      {name:"Texan Fish Finger",price:775,badge:"non-veg"},
      {name:"Fish Curry",price:795,badge:"non-veg"},
      {name:"Goan Fish Curry",price:795,badge:"non-veg"},
      {name:"Fish Kadhai",price:795,badge:"non-veg"},
    ]},
    { label:"Sizzlers — Veg", emoji:"🫕", tab:"sizzler", items:[
      {name:"Veg Chinese Sizzler",price:585,badge:"veg"},
      {name:"Paneer Steak Sizzler",price:635,badge:"veg"},
      {name:"Veg Tandoori Sizzler",price:595,badge:"veg"},
    ]},
    { label:"Sizzlers — Non Veg", emoji:"🍗", tab:"sizzler", items:[
      {name:"Chicken Chinese Sizzler",price:655,badge:"non-veg"},
      {name:"Chicken Tandoori Sizzler",price:675,badge:"non-veg"},
      {name:"Fish Garlic Tikka Sizzler",price:795,badge:"non-veg"},
    ]},

    // PAGE 9 — Egg & Momos Veg
    { label:"Egg — Lajawab", emoji:"🥚", tab:"egg", items:[
      {name:"Egg Chilli",price:295,badge:"non-veg"},
      {name:"Egg Pakoda",price:275,badge:"non-veg"},
      {name:"Egg Lollipop",price:325,badge:"non-veg"},
      {name:"Crispy Egg Finger",price:325,badge:"non-veg"},
      {name:"Boiled Egg",price:155,badge:"non-veg"},
      {name:"Egg Bhurji",price:275,badge:"non-veg"},
      {name:"Egg Bhuna",price:335,badge:"non-veg"},
      {name:"Rice Paper Cheese Omelette",price:385,badge:"non-veg"},
      {name:"Irani Omelette",price:365,badge:"non-veg"},
      {name:"Tandoori Egg Roast",price:365,badge:"non-veg"},
      {name:"Omelette",price:185,badge:"non-veg"},
      {name:"Egg Schezwan",price:335,badge:"non-veg"},
    ]},
    { label:"Dumplings — Veg", emoji:"🥟", tab:"momos", items:[
      {name:"Veg Steam Momos / Fried Momos",price2:"245 / 255",badge:"veg"},
      {name:"Paneer Steam Momos / Paneer Fried Momos",price2:"345 / 365",badge:"veg"},
      {name:"Tandoori Paneer Momos",price:345,badge:"veg"},
      {name:"Momos Sauted in Hot Garlic Sauce",price:355,badge:"veg"},
      {name:"Schezwan Gravy Momos",price:355,badge:"veg"},
      {name:"Veg Chilli Momos / Paneer Chilli Momos",price2:"285 / 385",badge:"veg"},
    ]},

    // PAGE 10 — Momos Non Veg & Pasta & Raita
    { label:"Dumplings — Non Veg", emoji:"🍗", tab:"momos", items:[
      {name:"Chicken Steam Momos / Chicken Fried Momos",price2:"335 / 355",badge:"non-veg"},
      {name:"Tandoori Chicken Momos",price:375,badge:"non-veg"},
      {name:"Chicken Chilli Momos",price:395,badge:"non-veg"},
      {name:"Chicken Burnt Garlic Momos",price:410,badge:"non-veg"},
    ]},
    { label:"Pasta", emoji:"🍝", tab:"pasta", items:[
      {name:"Pasta Alfredo",desc:"Veg / Chicken",price2:"365 / 415",badge:"veg"},
      {name:"Pasta Alla Arrabiata",desc:"Veg / Chicken",price2:"365 / 415",badge:"veg"},
      {name:"Mixed Sauce Pasta",desc:"Veg / Chicken",price2:"365 / 415",badge:"veg"},
      {name:"Lasagna",desc:"Veg / Chicken",price2:"495 / 595",badge:"veg"},
    ]},
    { label:"Raita & Curd", emoji:"🥛", tab:"raita", items:[
      {name:"Boondi Raita",price:155,badge:"veg"},
      {name:"Mix Veg Raita",price:155,badge:"veg"},
      {name:"Pineapple Raita",price:185,badge:"veg"},
      {name:"Curd Bowl",price:135,badge:"veg"},
    ]},

    // PAGE 11 — Papad & Salad
    { label:"Papad", emoji:"🫓", tab:"papad", items:[
      {name:"Roasted Papad",price:42,badge:"veg"},
      {name:"Fried Papad",price:45,badge:"veg"},
      {name:"Roasted Masala Papad",price:50,badge:"veg"},
      {name:"Fried Masala Papad",price:50,badge:"veg"},
      {name:"Papad Jaipuri",price:125,badge:"veg"},
      {name:"Nagli Papad",price:65,badge:"veg"},
      {name:"Nagli Masala Papad",price:75,badge:"veg"},
      {name:"Mayonnaise Nagli Masala Papad",price:115,badge:"veg"},
    ]},
    { label:"Salad", emoji:"🥗", tab:"salad", items:[
      {name:"Green Salad",price:145,badge:"veg"},
      {name:"Russian Salad",price:185,badge:"veg"},
      {name:"Cucumber Salad",price:135,badge:"veg"},
      {name:"American Corn Salad",price:235,badge:"veg"},
    ]},

    // PAGE 12 — Accompaniments & Italian/Mexican
    { label:"Accompaniments", emoji:"🧂", tab:"accomp", items:[
      {name:"Chana Roast with Garlic Fry",price:275,badge:"veg"},
      {name:"Chakna Platter",price:225,badge:"veg"},
      {name:"Kashmiri Chana Roast with Garlic Fry",price:295,badge:"veg"},
      {name:"Peanut Chaat (Boiled / Fry)",price:225,badge:"veg"},
      {name:"French Fries",price:225,badge:"veg"},
      {name:"Kashmiri Finger Chips",price:245,badge:"veg"},
      {name:"Garlic Fry",price:135,badge:"veg"},
      {name:"Green Chilli Fry",price:65,badge:"veg"},
      {name:"Extra Sauce (Garlic Mayo / Schezwan / Starter Sauce)",price:45,badge:"veg"},
    ]},
    { label:"Italian & Mexican", emoji:"🍕", tab:"italian", items:[
      {name:"Margarita Pizza",price:375,badge:"veg"},
      {name:"Veggie Delight Pizza",price:375,badge:"veg"},
      {name:"Spicy Paneer Tikka Pizza",price:435,badge:"veg"},
      {name:"Chicken Tikka Pizza",price:475,badge:"non-veg"},
      {name:"Sky Lounge Pizza",desc:"Veg / Non Veg",price2:"435 / 525",badge:"veg"},
      {name:"Mexican Pizza",desc:"Veg / Chicken",price2:"395 / 445",badge:"veg"},
      {name:"Peri Peri Pizza",desc:"Veg / Chicken",price2:"415 / 465",badge:"veg"},
      {name:"Burrito",desc:"Veg / Chicken",price2:"395 / 465",badge:"veg"},
      {name:"Nachos",price:375,badge:"veg"},
    ]},

    // PAGE 13 — Main Course Veg
    { label:"Main Course — Veg", emoji:"🌱", tab:"main", items:[
      {name:"Veg Maratha",price:355,badge:"veg"},
      {name:"Subz-E Makhanwala",price:355,badge:"veg"},
      {name:"Chana Masala",price:315,badge:"veg"},
      {name:"Veg Diwani Handi",desc:"Chef's Special",price:355,badge:"veg"},
      {name:"Veg Khurchan",desc:"Chef's Special",price:395,badge:"veg"},
      {name:"Cheese Corn Palak",desc:"Chef's Special",price:395,badge:"veg"},
      {name:"Subz-E-Jalfrezi",price:395,badge:"veg"},
      {name:"Mushroom Do Pyaza",price:395,badge:"veg"},
      {name:"Mushroom Masala",price:365,badge:"veg"},
      {name:"Dum Aloo Punjabi",desc:"Chef's Special",price:365,badge:"veg"},
      {name:"Malai Kofta",price:395,badge:"veg"},
      {name:"Nargis Kofta",price:375,badge:"veg"},
      {name:"Veg Patiala",price:395,badge:"veg"},
      {name:"Kaju Mutter Handi",price:395,badge:"veg"},
      {name:"Navaratan Korma",price:415,badge:"veg"},
    ]},

    // PAGE 14 — Cottage Cheese Specials
    { label:"Cottage Cheese Specials", emoji:"🧀", tab:"main", items:[
      {name:"Paneer Rajwadi",desc:"Chef's Special",price:435,badge:"veg"},
      {name:"Paneer Khurchan",desc:"Chef's Special",price:435,badge:"veg"},
      {name:"Paneer Tikka Masala",price:415,badge:"veg"},
      {name:"Paneer Butter Masala",price:415,badge:"veg"},
      {name:"Paneer Angara",price:415,badge:"veg"},
      {name:"Paneer Razaki",desc:"Chef's Special",price:455,badge:"veg"},
      {name:"Shahi Paneer",price:435,badge:"veg"},
      {name:"Paneer Shaam Savera",desc:"Chef's Special",price:455,badge:"veg"},
      {name:"Cheese Butter Masala",price:415,badge:"veg"},
      {name:"Paneer Lahori",desc:"Chef's Special",price:435,badge:"veg"},
      {name:"Paneer Changezi",price:455,badge:"veg"},
      {name:"Shahi Matka Paneer",desc:"Chef's Special",price:475,badge:"veg"},
      {name:"Matka Paneer Chatkara",desc:"Chef's Special",price:475,badge:"veg"},
      {name:"Paneer Mussalam",price:455,badge:"veg"},
      {name:"Paneer Hyderabadi",price:435,badge:"veg"},
    ]},

    // PAGE 15 — Non Veg Delicacies
    { label:"Non-Veg Delicacies", emoji:"🍗", tab:"main", items:[
      {name:"Chicken Nasida",desc:"Chef's Special",price:565,badge:"non-veg"},
      {name:"Butter-E-Murgh",desc:"Boneless / With Bone",price:545,badge:"non-veg"},
      {name:"Kadhai Murgh",price:545,badge:"non-veg"},
      {name:"Chicken Bawarchi Handi",desc:"Chef's Special",price:565,badge:"non-veg"},
      {name:"Chicken Tukada (Lapetta)",price:565,badge:"non-veg"},
      {name:"Murgh Tikka Masala",desc:"Chef's Special",price:555,badge:"non-veg"},
      {name:"Chicken Leg Piece Masala",price:565,badge:"non-veg"},
      {name:"Murgh Warhadi",price:525,badge:"non-veg"},
      {name:"Murgh Ra-Ra",desc:"Chef's Special",price:555,badge:"non-veg"},
      {name:"Chicken Rogan Josh",price:545,badge:"non-veg"},
      {name:"Murgh Patiyala",price:545,badge:"non-veg"},
      {name:"Murgh Musslam",desc:"Chef's Special",price:1150,badge:"non-veg"},
      {name:"Murgh Lahori",price:565,badge:"non-veg"},
      {name:"Murgh Kolhapuri",price:545,badge:"non-veg"},
      {name:"Murgh Changezi",desc:"Boneless / With Bone",price:565,badge:"non-veg"},
      {name:"Matka Chatkara Chicken",desc:"Chef's Special",price:595,badge:"non-veg"},
      {name:"Matka Souji Mutton",desc:"Chef's Special",price:695,badge:"non-veg"},
      {name:"Mutton Handi",price:675,badge:"non-veg"},
      {name:"Mutton Rogan Josh",price:675,badge:"non-veg"},
      {name:"Mutton Ra-Ra Masala",desc:"Chef's Special",price:675,badge:"non-veg"},
      {name:"Mutton Bhuna",price:675,badge:"non-veg"},
    ]},

    // PAGE 16 — Breads & Dal
    { label:"Breads", emoji:"🍞", tab:"breads", items:[
      {name:"Tandoori Roti / Butter Roti",price2:"32 / 42",badge:"veg"},
      {name:"Butter Naan / Garlic Naan",price2:"68 / 78",badge:"veg"},
      {name:"Cheese Chilly Garlic Naan",price:115,badge:"veg"},
      {name:"Tawa Paratha / Butter Tawa Paratha",price2:"38 / 48",badge:"veg"},
      {name:"Butter Kulcha (Onion / Veg Aloo)",price:95,badge:"veg"},
      {name:"Laccha Paratha (Methi / Pudina / Ajwain)",price:85,badge:"veg"},
      {name:"Missi Roti",price:85,badge:"veg"},
      {name:"Phulka / Butter Phulka",price2:"32 / 42",badge:"veg"},
      {name:"Amritsari Kulcha",price:125,badge:"veg"},
      {name:"Stuffed Kulcha",price:135,badge:"veg"},
      {name:"Roti Basket",price:685,badge:"veg"},
    ]},
    { label:"Dal", emoji:"🫕", tab:"dal", items:[
      {name:"Dal Fry",price:175,badge:"veg"},
      {name:"Jeera Dal",price:195,badge:"veg"},
      {name:"Sky Lounge Tadka",price:225,badge:"veg"},
      {name:"Dal Tadka",price:210,badge:"veg"},
      {name:"Dal Makhani",price:265,badge:"veg"},
      {name:"Matka Ghee Tadka",price:250,badge:"veg"},
      {name:"Matka Makhan",price:295,badge:"veg"},
      {name:"Dal Kolhapuri",price:225,badge:"veg"},
      {name:"Dal Peshawari",price:245,badge:"veg"},
    ]},

    // PAGE 17 — Rice & Biryani
    { label:"Rice & Pulao", emoji:"🍚", tab:"rice", items:[
      {name:"Steam Rice",price:185,badge:"veg"},
      {name:"Jeera Rice",price:195,badge:"veg"},
      {name:"Onion Garlic Rice",price:225,badge:"veg"},
      {name:"Veg Pulao",price:265,badge:"veg"},
      {name:"Kashmiri Veg Pulao",price:350,badge:"veg"},
      {name:"Dal Khichadi",price:250,badge:"veg"},
      {name:"Butter Dal Khichadi",price:285,badge:"veg"},
      {name:"Masala Dal Khichadi",price:295,badge:"veg"},
      {name:"Chicken Zafrani Pulao",price:545,badge:"non-veg"},
    ]},
    { label:"Biryani", emoji:"🍛", tab:"rice", items:[
      {name:"Matka Veg Dum Biryani",price:445,badge:"veg"},
      {name:"Matka Paneer Tikka Dum Biryani",price:465,badge:"veg"},
      {name:"Matka Egg Dum Biryani",price:425,badge:"non-veg"},
      {name:"Matka Chicken Dum Biryani",price:565,badge:"non-veg"},
      {name:"Matka Mutton Dum Biryani",price:635,badge:"non-veg"},
      {name:"Chicken Tikka Biryani",price:595,badge:"non-veg"},
    ]},

    // PAGE 18 — Desserts & Beverages
    { label:"Desserts", emoji:"🍮", tab:"dessert", items:[
      {name:"Coconut Coin Roll",price:350,badge:"veg"},
      {name:"Caramel Custard",price:350,badge:"veg"},
      {name:"Sizzling Brownie",price:235,badge:"veg"},
      {name:"Brownie Sundae",price:275,badge:"veg"},
      {name:"Panna Cotta",desc:"Italian dessert of sweetened cream",price:350,badge:"veg"},
      {name:"Choice of Ice Cream Scoop",price:85,badge:"veg"},
    ]},
    { label:"Hot & Cold", emoji:"☕", tab:"dessert", items:[
      {name:"Cup of Tea / Coffee",price:65,badge:"veg"},
      {name:"Glass of Butter Milk",price:95,badge:"veg"},
      {name:"Royal Lassi",price:145,badge:"veg"},
      {name:"Fresh Lime Soda",price:125,badge:"veg"},
    ]},
  ]
};


// ══════════════════════════════════════
//  BAR MENU
// ══════════════════════════════════════
const BAR_MENU = {
  tabs: [
    { id:'all',       label:'All' },
    { id:'cocktails', label:'🍹 Cocktails' },
    { id:'mocktails', label:'🧃 Mocktails' },
    { id:'shots',     label:'🥃 Shots' },
    { id:'liquor',    label:'🥂 Spirits' },
    { id:'beer',      label:'🍺 Beer' },
    { id:'wine',      label:'🍷 Wine' },
  ],
  sections: [
    { label:"Cocktails", emoji:"🍹", tab:"cocktails", items:[
      {name:"Margrita",desc:"All time favorite with Tequila & Limey Orange",price:390},
      {name:"White Russian",desc:"Muddy water of Kahlua, Baileys and Triple Sec",price:415},
      {name:"Caiprirojka",desc:"Fresh & tangy with Mint, Lime & Vodka served on crushed ice",price:390},
      {name:"Mojito",desc:"Original Cuban Rum roll with fresh Mint, Lime & sweet fizz",price:410,badge:"popular"},
      {name:"Cosmopolitan",desc:"Excellent mix of Vodka, Triple Sec & Cranberry",price:410},
      {name:"Daiquiris",desc:"Simple Rum, Lime & Sugar served frozen or straight up",price:390},
      {name:"Pinacolda",desc:"Rum served with Pineapple, Vanilla Ice Cream & Coconut",price:410},
      {name:"Sangria",desc:"Red Wine, Brandy, Triple Sec with Orange Juice & Fresh Fruits",price:415},
      {name:"Planters Punch",desc:"Orange blend with White & Dark Rum",price:410},
      {name:"Dirty Martini",desc:"Amazing mix of Gin & Martini topped with Olive",price:390},
      {name:"Sex on the Beach",desc:"Cool mix of Cranberry, Orange Juice with Peach & Vodka",price:415},
      {name:"Blue Heaven",desc:"Excellent mix of Mandarin Vodka, White Rum, Coffee Liqueur, Blue Curacao & Pineapple Juice",price:410},
      {name:"Blue Berry Sour",desc:"Whiskey shake with White Sour & Blueberry",price:410},
      {name:"Purple Martini",desc:"Cool mix of Vodka, Black Currant with Black Grape",price:399},
    ]},
    { label:"Premium Cocktails", emoji:"✨", tab:"cocktails", items:[
      {name:"Long Island Ice Tea",desc:"Five whites & tangy cola splash packed with ice",price:565,badge:"popular"},
      {name:"Bull Frog",desc:"Energizing sweet sour drink — White Spirits, Red Bull & Blue Curacao",price:575},
      {name:"Miami Ice Tea",price:575},
    ]},
    { label:"Mocktails", emoji:"🧃", tab:"mocktails", items:[
      {name:"Daiquris",desc:"Make your choice — Kiwi, Strawberry, Lychee",price:290},
      {name:"Apple of My Eyes",desc:"Enjoy Apple with a splash of Coconut Milk, Lychee flavor",price:290},
      {name:"Green Juliet",desc:"Cranberry juice in company of Mint leaves & Lemon",price:290},
      {name:"Spicy Queen",desc:"Chilly flavored Kiwi — hot tangy mix of Pineapple juice",price:290},
      {name:"Muddy Water",desc:"Choco-Coffee thick shake",price:290,badge:"popular"},
      {name:"Lady in Red",desc:"Tangy sweet fizz with splash of Strawberry flavor",price:290},
      {name:"Pinako",desc:"Excellent mix of Pineapple juice, Orange juice topped with creamy Coconut Milk & Cucumber",price:290},
      {name:"Black Magic Moment",desc:"Splash of Black Currant crush mixed with Fresh Cream & Sprite",price:290},
      {name:"Tango N Cash",desc:"Blue Curacao, Black Grape Tang layered with Orange",price:290},
      {name:"Cinderella",desc:"Combo of Orange & Pineapple juice topped with Grenadine",price:290},
      {name:"Bora Bora",desc:"Cranberry juice & Apple juice mixed with splash of Lychee",price:290},
      {name:"Bull Fighter",desc:"Tangy sweet Strawberry crush topped with Red Bull",price:290},
    ]},
    { label:"Shooters", emoji:"🔥", tab:"shots", items:[
      {name:"Kamikaze",desc:"Vodka, Triple Sec & Lime — ask for your favorite flavor",price:250},
      {name:"B-52",desc:"Layered — Kahlua, Baileys & Orange Liqueur",price:369},
      {name:"Brain Hemorrhage",desc:"Peach flavored White Wine & Vodka",price:275},
      {name:"Fire Ball",desc:"Flaming layered Dark Rum with flavor Vodka",price:275},
      {name:"Flaming Lamborghini",desc:"Flaming tower",price:600,badge:"popular"},
      {name:"Alien Skull",desc:"Baileys sprinkled with Sambuca",price:375},
    ]},
    { label:"Shots & Liquors", emoji:"🥃", tab:"shots", items:[
      {name:"Camino Tequila",price:325},
      {name:"Sauza Silver",price:350},
      {name:"Sauza Gold",price:375},
      {name:"Jagermeister",price:359},
      {name:"Jager Bomb",price:565},
      {name:"Bailey Irish Cream",price:315},
      {name:"Cointreau",price:325},
      {name:"Kahlua",price:300},
      {name:"Sambuca",price:300},
    ]},
    { label:"Domestic Liquor", emoji:"🥂", tab:"liquor", tableFormat:true,
      columns:["Name","30ml","90ml","180ml","360ml"],
      rows:[
        ["Blenders Pride","125","350","725","1470"],
        ["Blenders Pride Reserve","145","425","850","1720"],
        ["Sterling Reserve B10","125","350","725","1470"],
        ["Signature","125","350","725","1470"],
        ["Antiquity Blue","145","425","850","1720"],
        ["American Pride","125","350","725","1470"],
        ["Smirnoff Vodka","145","425","850","1720"],
        ["Bacardi White","145","350","725","1720"],
        ["Bacardi Black","70","210","420","840"],
        ["Old Monk","70","210","420","840"],
        ["Old Monk Legend","145","425","850","1720"],
        ["Old Monk Supreme","90","270","540","1080"],
        ["Oaksmith Gold","145","425","850","1720"],
        ["Captain Morgan","70","210","420","840"],
        ["Magic Dazzle","150","450","900","1800"],
        ["Legacy","130","390","780","1560"],
    ]},
    { label:"Imported Liquor", emoji:"🌍", tab:"liquor", tableFormat:true,
      columns:["Name","30ml","90ml","180ml","360ml"],
      rows:[
        ["100 Pipers","225","675","1350","2650"],
        ["100 Pipers 12 Yr","275","825","1470","3300"],
        ["Ballantine","225","675","1350","2650"],
        ["Chivas Regal","280","840","1680","3360"],
        ["Ballantine 12 Yr","280","840","1680","3360"],
        ["Jack Daniel","300","900","1800","3600"],
        ["Royal Ranthambore","225","675","1350","2650"],
        ["Dewar's White Label","199","597","1185","2350"],
        ["William Lawsons","199","597","1185","2350"],
        ["Black Dog (Gold)","280","840","1680","3360"],
        ["Black Dog 8 Year","225","675","1350","2650"],
        ["VAT 69","225","675","1350","2650"],
        ["J & B (Rare)","225","675","1350","2650"],
        ["Black & White","225","675","1350","2650"],
        ["Red Label","225","675","1350","2650"],
        ["Teacher's Highland","225","675","1350","2650"],
        ["Teacher's 50","275","825","1470","3300"],
        ["Jim Beam","250","750","1500","3000"],
        ["Grey Goose","310","930","1860","3720"],
        ["Absolute","225","675","1350","2650"],
        ["Black Label","275","825","1470","3300"],
    ]},
    { label:"Imported / Single Malt", emoji:"🏔", tab:"liquor", tableFormat:true,
      columns:["Name","30ml","90ml","180ml","360ml"],
      rows:[
        ["The Glenlivet","400","1200","2400","4800"],
        ["Talisker","425","1275","2550","5100"],
        ["Double Black","425","1275","2550","5100"],
        ["Singleton","425","1275","2550","5100"],
        ["Glenfiddich","425","1275","2550","5100"],
    ]},
    { label:"Gin", emoji:"🌿", tab:"liquor", tableFormat:true,
      columns:["Name","30ml","90ml","180ml","360ml"],
      rows:[
        ["Bombay Sapphire","190","570","1140","2280"],
        ["Jaisalmer","195","585","1170","2340"],
        ["Beefeater Gin","130","390","780","1560"],
        ["Blue Rebond","50","150","300","600"],
    ]},
    { label:"Beer — Strong", emoji:"🍺", tab:"beer", tableFormat:true,
      columns:["Name","650ml","500ml","330ml","Tower"],
      rows:[
        ["Magnum","425","—","265","1650"],
        ["Elephant","425","325","—","1650"],
        ["Tuborg","315","250","—","1150"],
        ["Kingfisher","315","—","175","1150"],
    ]},
    { label:"Beer — Mild", emoji:"🍻", tab:"beer", tableFormat:true,
      columns:["Name","650ml","500ml","330ml","Tower"],
      rows:[
        ["Corona","—","—","375","2275"],
        ["Hoegaarden","—","—","375","2275"],
        ["Heineken","315","250","210","1150"],
        ["Budweiser","410","—","230","1550"],
        ["Carlsburg","410","250","—","1550"],
        ["Tuborg (Mild)","410","250","—","1550"],
        ["Kingfisher Ultra","309","—","—","1150"],
        ["Kingfisher Mild","309","—","—","1150"],
    ]},
    { label:"Others", emoji:"🥤", tab:"beer", items:[
      {name:"Breezer (All Flavours)",price:210},
      {name:"Tonic Water",price:150},
      {name:"Red Bull",price:180},
    ]},
    { label:"Wine", emoji:"🍷", tab:"wine", tableFormat:true,
      columns:["Name","750ml","375ml"],
      rows:[
        ["Jacob Creek Red","2500","—"],
        ["Sula Seco (Rose)","—","1200"],
        ["Sula Seco (Classic)","—","1200"],
        ["Sula Dindori","2000","1000"],
        ["Sula Chenin Blanc","1200","700"],
        ["Sula Zinfandel / Rose","1200","700"],
        ["Sula Lateharvest (White)","1700","900"],
        ["Sula Cabernet Siraz","1500","800"],
    ]},
  ]
};
